# Configuración para el Worker Node (Servidor y Cliente)
# Dónde escucha tareas del Master
WorkerAdapter.Endpoints=tcp -h localhost -p 10002

# Dónde reporta los resultados al Master
Master.Proxy=Master:tcp -h localhost -p 10001
