# Configuración para el Event Processor (Servidor y Cliente)
# Dónde escucha a los buses
EventProcessorAdapter.Endpoints=tcp -h localhost -p 10000

# Dónde envía los datos para archivo
ArchiveService.Proxy=ArchiveService:tcp -h localhost -p 10001
