# Configuración para el Visualizer Client (Servidor y Cliente)
# Dónde escucha los callbacks de tiempo real
VisualizerCallbackAdapter.Endpoints=tcp -h localhost

# Dónde se suscribe para streaming
RealTimeStreaming.Proxy=RealTimeStreaming:tcp -h localhost -p 10000

# Dónde consulta los reportes
QueryProvider.Proxy=QueryProvider:tcp -h localhost -p 10001
