plugins {
    id 'java'
    id 'com.zeroc.gradle.ice-builder.slice' version '1.5.0' apply false
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(11)
        }
    }

    dependencies {
        implementation 'com.zeroc:ice:3.7.10'
    }

    // Configuración específica para proyectos que son aplicaciones
    if (project.name != 'contracts') {
        apply plugin: 'application'
        
        dependencies {
            implementation project(':contracts')
        }

        application {
            if (project.name == 'bus-simulator') {
                mainClass = 'sim.BusSimulator'
            } else if (project.name == 'event-processor') {
                mainClass = 'processor.EventProcessor'
            } else if (project.name == 'data-center') {
                mainClass = 'center.DataCenterMaster'
            } else if (project.name == 'worker-node') {
                mainClass = 'worker.WorkerNode'
            } else if (project.name == 'visualizer-client') {
                mainClass = 'visualizer.VisualizerClient'
            }
        }
    }
}
